create table if not exists public.runs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source_hash text not null,
    weights jsonb not null,
    thresholds jsonb not null,
    quality jsonb not null,
    ranking jsonb not null
);

create table if not exists public.cases (
    id bigint generated by default as identity primary key,
    sku text not null,
    run_id bigint,
    status text not null check (status in ('novo', 'em_investigacao', 'aguardando_comercial', 'aguardando_producao', 'concluido')),
    owner text not null default '',
    due_date text not null default '',
    action text not null default '',
    note text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.case_history (
    id bigint generated by default as identity primary key,
    case_id bigint not null references public.cases(id) on delete cascade,
    status text not null check (status in ('novo', 'em_investigacao', 'aguardando_comercial', 'aguardando_producao', 'concluido')),
    owner text not null default '',
    due_date text not null default '',
    action text not null default '',
    note text not null default '',
    changed_at timestamptz not null default now()
);

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    sku text not null,
    action text not null check (action in ('aceita', 'alterada', 'rejeitada', 'investigar')),
    note text not null default '',
    user_name text not null default '',
    partner_data_effect text not null default 'nao_utilizado'
        check (partner_data_effect in ('nao_utilizado', 'confirmou', 'aumentou_confianca', 'alterou_decisao')),
    analysis_minutes integer check (analysis_minutes is null or analysis_minutes >= 0),
    created_at timestamptz not null default now()
);

create index if not exists cases_updated_at_idx on public.cases (updated_at desc);
create index if not exists case_history_case_id_id_idx on public.case_history (case_id, id desc);
create index if not exists feedback_id_idx on public.feedback (id desc);
create index if not exists runs_id_idx on public.runs (id desc);

alter table public.runs enable row level security;
alter table public.cases enable row level security;
alter table public.case_history enable row level security;
alter table public.feedback enable row level security;

comment on table public.runs is 'Snapshots auditáveis do ranking do Caderno Inteligente.';
comment on table public.cases is 'Casos operacionais acompanhados pelo PCP.';
comment on table public.case_history is 'Histórico imutável das alterações de casos.';
comment on table public.feedback is 'Decisões humanas registradas separadamente da planilha de origem.';
